spring:
  application:
    name: turbin
  rabbitmq:
    host: 192.168.244.131
    port: 5672
    username: admin
    password: admin
server:
  port: 5001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
turbine:
  app-config: order-service,feign,zuul
  cluster-name-expression: new String("default")
